name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-matrix:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python_version:
          - "3.9"
          - "3.12"
    defaults:
      run:
        shell: bash
    name: Run Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install --no-interaction
      - name: Run tests with pytest
        run: |
          poetry run pytest
